version: "3.8"

services:
  musicbrainz:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - app/.env
    volumes:
      - ./app:/app
      - music_db:/app/data
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  music_db:
    name: music_db
